service: serverless-task-api
provider:
  name: aws
  runtime: nodejs16.x
functions:
  getTasks:
    handler: src/handler.getTasks
    events:
      - http:
          path: tasks
          method: get
  createTask:
    handler: src/handler.createTask
    events:
      - http:
          path: tasks
          method: post
resources:
  Resources:
    TasksDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Tasks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
