# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # override any inherited proxy vars
    env:
      http_proxy: ""
      https_proxy: ""

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Clear npm proxy config
        run: |
          npm config delete proxy
          npm config delete https-proxy

      - name: Setup Node.js & enable cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'        # auto-caches ~/.npm between runs

      - name: Install dependencies
        run: npm ci         # fast, reproducible install

      - name: Run tests
        run: npm test
